
services:
  demo-docker-aws:
    build: .
    container_name: demo-docker-aws
    ports:
      # Mapeia a porta 80 da máquina EC2 (Internet) para a porta 8080 do container (Spring Boot)
      - "80:8080"
    restart: unless-stopped